# use images from jupyter
FROM jupyter/datascience-notebook:4d70cf8da953

# set user
USER root

# install ubuntu packages
RUN apt-get update && \
    apt-get install -y \
    bash \
    wget \
    patch \
    libmagick++-dev \
    libhdf5-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libpng-dev \
    libxt-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libglpk40 \
    libgit2-dev \
    libgsl-dev \
    jags \
    libgsl27 && \
    rm -rf /var/lib/apt/lists/*
    
# install python packages
RUN pip install anndata
RUN pip install scanpy
RUN pip install pyranges
RUN pip install pybiomart
RUN pip install leidenalg
RUN pip install pyscenic
RUN pip install anndata2ri
RUN pip install numpy==1.23.5  --ignore-installed
