# use images from rocker
FROM rocker/rstudio:4.3.2

# install ubuntu packages 
RUN apt-get update && \
    apt-get install -y \
    bash \
    patch \
    libmagick++-dev \
    libhdf5-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libpng-dev \
    libxt-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libglpk40 \
    libgit2-dev \
    libgsl27 \
    libgsl-dev

# install R packages
RUN Rscript -e "install.packages(c('BiocManager', 'devtools'))"
RUN Rscript -e "install.packages(c('remotes', 'curl', 'RCurl', 'magick', 'openssl', 'igraph', 'leiden', 'httr', 'plotly', 'circlize', 'ggalluvial', 'ggbeeswarm', 'ggpubr', 'ggrepel', 'harmony', 'jsonlite', 'languageserver', 'Matrix', 'patchwork', 'RColorBrewer', 'reticulate', 'RSQLite', 'rstatix', 'scales', 'Seurat', 'SeuratObject', 'Signac', 'SoupX', 'UpSetR', 'tidyverse', 'hdf5r', 'fastTopics'), dependencies = TRUE)"
RUN Rscript -e "BiocManager::install(c('BiocParallel', 'BSgenome.Hsapiens.UCSC.hg38', 'chromVAR', 'ComplexHeatmap', 'DESeq2', 'EnsDb.Hsapiens.v86', 'HCATonsilData', 'JASPAR2024', 'limma', 'JASPAR2020', 'biovizBase', 'TFBSTools', 'edgeR', 'scater', 'SingleR', 'scDblFinder'))" 
RUN Rscript -e "remotes::install_github('mojaveazure/seurat-disk')"
RUN Rscript -e "remotes::install_github('morinlab/GAMBLR.data')"
RUN Rscript -e "remotes::install_github('massonix/SLOcatoR')"
RUN Rscript -e "remotes::install_github('satijalab/azimuth', ref = 'master')"
RUN Rscript -e "remotes::install_github('stuart-lab/signac', ref = 'develop')"

# install R packages
RUN apt-get install -y jags
RUN Rscript -e "BiocManager::install(c('infercnv'))"

# create venv
RUN apt-get install -y \
    python3 \
    python3-venv \
    python3-pip
RUN python3 -m venv /home/rstudio/venv
RUN chmod -R 755 /home/rstudio

# install python packages in venv
RUN /home/rstudio/venv/bin/pip3 install pandas
RUN /home/rstudio/venv/bin/pip3 install numpy
RUN /home/rstudio/venv/bin/pip3 install leidenalg

# install python packages
RUN pip install MACS2
RUN pip install numpy
RUN pip install Cython
RUN chmod -R 777 /usr/local/lib/python3.10/dist-packages/MACS2