# use images from rocker
FROM bioconductor/bioconductor_docker:3.18

# add environment variables
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# install ubuntu packages
RUN apt-get update \
    && apt-get install -y -f --no-install-recommends python3-pip \
    && apt-get install -y -f --no-install-recommends python3-venv

# create venv
RUN python3 -m venv /home/rstudio/venv \
    && chmod -R 777 /home/rstudio
ENV VIRTUAL_ENV=/home/rstudio/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# install python packages in venv
RUN $VIRTUAL_ENV/bin/pip install pandas==2.2.2 \
    && $VIRTUAL_ENV/bin/pip install numpy==1.26.4 \
    && $VIRTUAL_ENV/bin/pip install leidenalg==0.10.2 \
    && $VIRTUAL_ENV/bin/pip install scanpy==1.10.1

# install python packages globally
RUN pip install MACS2==2.2.9.1

# install R packages
RUN Rscript -e "install.packages('BiocManager')" -e "library('BiocManager')"
RUN Rscript -e "install.packages('remotes')" -e "library('remotes')"
RUN Rscript -e "install.packages('devtools')" -e "library('devtools')"
RUN Rscript -e "install.packages('magick')" -e "library(magick)"
RUN Rscript -e "install.packages('harmony')" -e "library('harmony')"
RUN Rscript -e "install.packages('circlize')" -e "library('circlize')"
RUN Rscript -e "install.packages('ggalluvial')" -e "library('ggalluvial')"
RUN Rscript -e "install.packages('ggbeeswarm')" -e "library('ggbeeswarm')"
RUN Rscript -e "install.packages('languageserver')" -e "library('languageserver')"
RUN Rscript -e "install.packages('tidyverse')" -e "library('tidyverse')"
RUN Rscript -e "install.packages('ggrastr')" -e "library('ggrastr')"
RUN Rscript -e "install.packages('randomcoloR')" -e "library('randomcoloR')"
RUN Rscript -e "install.packages('concaveman')" -e "library('concaveman')"
RUN Rscript -e "install.packages('geometry')" -e "library('geometry')"
RUN Rscript -e "install.packages('hdf5r')" -e "library('hdf5r')"
RUN Rscript -e "install.packages('shinyBS')" -e "library('shinyBS')"
RUN Rscript -e "BiocManager::install('ComplexHeatmap')" -e "library('ComplexHeatmap')"
RUN Rscript -e "BiocManager::install('limma')" -e "library('limma')"
RUN Rscript -e "BiocManager::install('edgeR')" -e "library('edgeR')"
RUN Rscript -e "BiocManager::install('scater')" -e "library('scater')"
RUN Rscript -e "BiocManager::install('fgsea')" -e "library('fgsea')"
RUN Rscript -e "BiocManager::install('BSgenome.Hsapiens.UCSC.hg38')" -e "library('BSgenome.Hsapiens.UCSC.hg38')"
RUN Rscript -e "BiocManager::install('HCATonsilData')" -e "library('HCATonsilData')"
RUN Rscript -e "BiocManager::install('CNEr')" -e "library('CNEr')"
RUN Rscript -e "BiocManager::install('TFBSTools', type = 'source', force = TRUE)" -e "library('TFBSTools')"
RUN Rscript -e "remotes::install_github('satijalab/seurat-wrappers')"
RUN Rscript -e "remotes::install_github('mojaveazure/seurat-disk')"
RUN Rscript -e "remotes::install_github('satijalab/azimuth')" -e "library(Azimuth)"
RUN Rscript -e "remotes::install_github('ajiangsfu/PRPS')" -e "library(PRPS)"
RUN Rscript -e "remotes::install_github('jinworks/CellChat')" -e "library(CellChat)"
RUN Rscript -e "remotes::install_github('drieslab/GiottoUtils', upgrade = 'never', ref = 'bec3c79398a9aff299a01cc152ff6f2245a8f965')" -e "library(GiottoUtils)"
RUN Rscript -e "remotes::install_github('drieslab/GiottoClass', upgrade = 'never', ref = '6d9d385beebcc57b78d34ffbe30be1ef0a184681')" -e "library(GiottoClass)"
RUN Rscript -e "remotes::install_github('Nanostring-Biostats/FastReseg', ref = 'main', dependencies = FALSE)" -e "library(FastReseg)"

# clear cache
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*