# Use images from jupyter
FROM jupyter/scipy-notebook:python-3.11
USER root

# Install ubuntu packages
RUN apt-get update \
    && apt-get install -y -f --no-install-recommends default-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add snakemake environment variables
ENV XDG_CACHE_HOME=/tmp

# Install python packages
RUN pip install pandas==2.1.1
RUN pip install numpy==1.26.4
RUN pip install leidenalg==0.10.2
RUN pip install scanpy==1.10.4
RUN pip install scikit-misc==0.5.1
RUN pip install harmonypy==0.0.10
RUN pip install dask==2024.11.2
RUN pip install squidpy==1.6.2
RUN pip install randomcolor==0.4.4.6
RUN pip install matplotlib==3.9.2
RUN pip install opencv-python==4.11.0.86
RUN pip install scikit-image==0.23.2
RUN pip install cellpose==4.0.2
RUN pip install pydeseq2==0.5.1
RUN pip install gseapy==1.1.9
RUN pip install lxml==6.0.2
RUN pip install cellphonedb==5.0.1
RUN pip install adjustText==1.3.0