# use images from jupyter
FROM jupyter/scipy-notebook:python-3.11

# set user
USER root

# install ubuntu packages
RUN apt-get update && \
    apt-get install -y \
    bash \
    wget \
    default-jdk \
    openjdk-8-jdk

# add snakemake environment variables
ENV XDG_CACHE_HOME=/tmp

# install python packages
RUN pip install pandas==2.2.2
RUN pip install numpy==1.26.4
RUN pip install leidenalg==0.10.2
RUN pip install scanpy==1.10.4
RUN pip install squidpy==1.6.2
RUN pip install randomcolor==0.4.4.6
RUN pip install scikit-misc==0.5.1
RUN pip install wget==3.2
RUN pip install matplotlib==3.9.2
RUN pip install harmonypy==0.0.10